// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_tweets_
SEXP read_tweets_(const std::string& file_path);
RcppExport SEXP _tweetio_read_tweets_(SEXP file_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file_path(file_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_tweets_(file_path));
    return rcpp_result_gen;
END_RCPP
}
// prep_bbox_
Rcpp::List prep_bbox_(const Rcpp::List& bbox_coords);
RcppExport SEXP _tweetio_prep_bbox_(SEXP bbox_coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type bbox_coords(bbox_coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_bbox_(bbox_coords));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tweetio_read_tweets_", (DL_FUNC) &_tweetio_read_tweets_, 1},
    {"_tweetio_prep_bbox_", (DL_FUNC) &_tweetio_prep_bbox_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tweetio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
