# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.is_valid_point <- function(geo_coords) {
    .Call(`_tweetio_is_valid_point`, geo_coords)
}

.is_valid_bbox <- function(bbox_coords) {
    .Call(`_tweetio_is_valid_bbox`, bbox_coords)
}

.prep_bbox <- function(bbox_coords) {
    .Call(`_tweetio_prep_bbox`, bbox_coords)
}

.read_tweets <- function(file_paths, verbose, batch_size, reserve) {
    .Call(`_tweetio_read_tweets`, file_paths, verbose, batch_size, reserve)
}

unnest_entities2_impl <- function(tracker, source, target, col_names) {
    .Call(`_tweetio_unnest_entities2_impl`, tracker, source, target, col_names)
}

.unnest_edges <- function(user_id, target, status_id, created_at) {
    .Call(`_tweetio_unnest_edges`, user_id, target, status_id, created_at)
}

