# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_tweets_ <- function(file_path) {
    .Call(`_tweetio_read_tweets_`, file_path)
}

prep_bbox_ <- function(bbox_coords) {
    .Call(`_tweetio_prep_bbox_`, bbox_coords)
}

flatten_date_users_ <- function(date, user_id, screen_name) {
    .Call(`_tweetio_flatten_date_users_`, date, user_id, screen_name)
}

