on:
  push

name: coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { compiler: g++-8 }

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: System Dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get update -y
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt install \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sudo apt-get install ${{ matrix.config.compiler }} -y
          mkdir -p ~/.R/
          echo $'CXX1X=g++-8\nCXX17=${{ matrix.config.compiler }}\nCXX14=${{ matrix.config.compiler }}\nCXX11=${{ matrix.config.compiler }}' >> ~/.R/Makevars


      - name: Prep R
        shell: Rscript {0}
        run: |
          if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("curl", dependencies = TRUE)
          remotes::install_cran("covr", dependencies = TRUE)
          remotes::install_local()


      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
